[package]
name = "backend"
version = "0.5.1"
edition = "2024"

[dependencies]
# Async runtime
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }
tokio-util = { version = "0.7", features = ["io"] }

# Database connection
diesel = { version = "2.3", features = ["postgres", "uuid", "chrono", "serde_json"] }
deadpool-diesel = { version = "0.6", features = ["postgres"] }
diesel-derive-enum = { version = "2", features = ["postgres"] }

# HTTP server / API
axum = "0.8"
tower-http = { version = "0.6", features = ["cors"] }
jsonwebtoken = { version = "10", features = ["rust_crypto"] }

# Parsing and types
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
base64 = "0.22"
bitflags = { version = "2", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["serde", "rng", "v4"] }

# Observability
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-opentelemetry = "0.32"
opentelemetry = "0.31"
opentelemetry_sdk = "0.31"
opentelemetry-otlp = { version = "0.31", features = ["grpc-tonic"] }
opentelemetry-appender-tracing = { version = "0.31", features = ["tracing-opentelemetry"] }

# Other
exn = "0.3"
fast_qr = { version = "0.13", features = ["image"] }
ipnet = { version = "2", features = ["serde"] }
toml = "1.1.2"

[profile.release]
lto = 'fat' # Perform link time optimizations for the whole dependency graph
codegen-units = 1 # Sacrifice compilation speed for a faster binary

[lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
